=== eXigentCoder/swagger-spec-express/lib/schemas/json-schema-6.0.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://json-schema.org/draft-06/schema#",
  "title": "Core schema meta-schema",
  "definitions": {
    "schemaArray": {
      "type": "array",
      "minItems": 1,
      "items": {"$ref": "#"}
    },
    "nonNegativeInteger": {
      "type": "integer",
      "minimum": 0
    },
    "nonNegativeIntegerDefault0": {
      "allOf": [{"$ref": "#/definitions/nonNegativeInteger"}, {"default": 0}]
    },
    "simpleTypes": {
      "enum": ["array", "boolean", "integer", "null", "number", "object", "string"]
    },
    "stringArray": {
      "type": "array",
      "items": {"type": "string"},
      "uniqueItems": true,
      "default": []
    }
  },
  "type": ["object", "boolean"],
  "properties": {
    "$id": {
      "type": "string",
      "format": "uri-reference"
    },
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "$ref": {
      "type": "string",
      "format": "uri-reference"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "default": {},
    "multipleOf": {
      "type": "number",
      "exclusiveMinimum": 0
    },
    "maximum": {
      "type": "number"
    },
    "exclusiveMaximum": {
      "type": "number"
    },
    "minimum": {
      "type": "number"
    },
    "exclusiveMinimum": {
      "type": "number"
    },
    "maxLength": {"$ref": "#/definitions/nonNegativeInteger"},
    "minLength": {"$ref": "#/definitions/nonNegativeIntegerDefault0"},
    "pattern": {
      "type": "string",
      "format": "regex"
    },
    "additionalItems": {"$ref": "#"},
    "items": {
      "anyOf": [{"$ref": "#"}, {"$ref": "#/definitions/schemaArray"}],
      "default": {}
    },
    "maxItems": {"$ref": "#/definitions/nonNegativeInteger"},
    "minItems": {"$ref": "#/definitions/nonNegativeIntegerDefault0"},
    "uniqueItems": {
      "type": "boolean",
      "default": false
    },
    "contains": {"$ref": "#"},
    "maxProperties": {"$ref": "#/definitions/nonNegativeInteger"},
    "minProperties": {"$ref": "#/definitions/nonNegativeIntegerDefault0"},
    "required": {"$ref": "#/definitions/stringArray"},
    "additionalProperties": {"$ref": "#"},
    "definitions": {
      "type": "object",
      "additionalProperties": {"$ref": "#"},
      "default": {}
    },
    "properties": {
      "type": "object",
      "additionalProperties": {"$ref": "#"},
      "default": {}
    },
    "patternProperties": {
      "type": "object",
      "additionalProperties": {"$ref": "#"},
      "default": {}
    },
    "dependencies": {
      "type": "object",
      "additionalProperties": {
        "anyOf": [{"$ref": "#"}, {"$ref": "#/definitions/stringArray"}]
      }
    },
    "propertyNames": {"$ref": "#"},
    "const": {},
    "enum": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true
    },
    "type": {
      "anyOf": [
        {"$ref": "#/definitions/simpleTypes"},
        {
          "type": "array",
          "items": {"$ref": "#/definitions/simpleTypes"},
          "minItems": 1,
          "uniqueItems": true
        }
      ]
    },
    "format": {"type": "string"},
    "allOf": {"$ref": "#/definitions/schemaArray"},
    "anyOf": {"$ref": "#/definitions/schemaArray"},
    "oneOf": {"$ref": "#/definitions/schemaArray"},
    "not": {"$ref": "#"}
  },
  "default": {}
}

=== eXigentCoder/swagger-spec-express/lib/schemas/tag.json
{
  "title": "Tag",
  "type": "object",
  "additionalProperties": false,
  "required": ["name"],
  "properties": {
    "name": {
      "type": "string",
      "description": "Required. The name of the tag."
    },
    "description": {
      "type": "string",
      "description": "A short description for the tag. GFM syntax can be used for rich text representation."
    },
    "externalDocs": {
      "$ref": "#/definitions/externalDocs"
    }
  },
  "patternProperties": {
    "^x-": {
      "$ref": "#/definitions/vendorExtension"
    }
  },
  "definitions": {
    "externalDocs": {
      "type": "object",
      "additionalProperties": false,
      "description": "information about external documentation",
      "required": ["url"],
      "properties": {
        "description": {
          "type": "string",
          "description": "A short description of the target documentation. GFM syntax can be used for rich text representation."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Required. The URL for the target documentation. Value MUST be in the format of a URL."
        }
      },
      "patternProperties": {
        "^x-": {
          "$ref": "#/definitions/vendorExtension"
        }
      }
    },
    "vendorExtension": {
      "description": "Any property starting with x- is valid.",
      "additionalProperties": true,
      "additionalItems": true
    }
  },
  "description": "Allows adding meta data to a single tag that is used by the Operation Object. It is not mandatory to have a Tag Object per tag used there.",
  "$id": "https://raw.githubusercontent.com/eXigentCoder/swagger-spec-express/master/lib/schemas/tag.json"
}

=== eXigentCoder/swagger-spec-express/lib/schemas/query-parameter-sub-schema.json
{
  "title": "Query parameter sub schema",
  "type": "object",
  "required": ["name", "in", "type"],
  "additionalProperties": false,
  "patternProperties": {
    "^x-": {
      "$ref": "#/definitions/vendorExtension"
    }
  },
  "properties": {
    "required": {
      "type": "boolean",
      "description": "Determines whether or not this parameter is required or optional.",
      "default": false
    },
    "in": {
      "type": "string",
      "description": "Determines the location of the parameter.",
      "enum": ["query"]
    },
    "description": {
      "type": "string",
      "description": "A brief description of the parameter. This could contain examples of use.  GitHub Flavored Markdown is allowed."
    },
    "name": {
      "type": "string",
      "description": "The name of the parameter."
    },
    "allowEmptyValue": {
      "type": "boolean",
      "default": false,
      "description": "allows sending a parameter by name only or with an empty value."
    },
    "type": {
      "type": "string",
      "enum": ["string", "number", "boolean", "integer", "array"],
      "description": "**Required.** The type of the parameter. Since the parameter is not located at the request body, it is limited to simple types (that is, not an object). The value MUST be one of `string`, `number`, `integer`, `boolean`, `array` or `file`. If type is `file`, the [consumes](http://swagger.io/specification/#operationConsumes) MUST be either `multipart/form-data`, `application/x-www-form-urlencoded` or both and the parameter MUST be in `formData`."
    },
    "format": {
      "type": "string",
      "description": "The extending format for the previously mentioned [type](http://swagger.io/specification/#parameterType). See [Data Type Formats](http://swagger.io/specification/#dataTypeFormat) for further details."
    },
    "items": {
      "$ref": "#/definitions/primitivesItems",
      "description": "Required if [type](http://swagger.io/specification/#parameterType) is `array`. Describes the type of items in the array."
    },
    "collectionFormat": {
      "$ref": "#/definitions/collectionFormatWithMulti",
      "description": "Determines the format of the array if type array is used. Possible values are:\r\n\r\n- csv comma separated values foo,bar.\r\n- ssv space separated values foo bar.\r\n- tsv tab separated values foo\tbar.\r\n- pipes pipe separated values foo|bar.\r\n- multi corresponds to multiple parameter instances instead of multiple values for a single instance foo=bar&foo=baz. This is valid only for parameters in `query` or `formData`.\r\n\r\nDefault value is csv."
    },
    "default": {
      "$ref": "#/definitions/default",
      "description": "Declares the value of the parameter that the server will use if none is provided, for example a `count` to control the number of results per page might default to 100 if not supplied by the client in the request. (Note: `default` has no meaning for required parameters.) See [http://json-schema.org/latest/json-schema-validation.html#anchor101](http://json-schema.org/latest/json-schema-validation.html#anchor101). Unlike JSON Schema this value MUST conform to the defined type for this parameter."
    },
    "maximum": {
      "$ref": "#/definitions/maximum",
      "description": "See [json-schema.org](http://json-schema.org/latest/json-schema-validation.html#anchor17)."
    },
    "exclusiveMaximum": {
      "$ref": "#/definitions/exclusiveMaximum",
      "description": "See [json-schema.org](http://json-schema.org/latest/json-schema-validation.html#anchor17)."
    },
    "minimum": {
      "$ref": "#/definitions/minimum",
      "description": "See [json-schema.org](http://json-schema.org/latest/json-schema-validation.html#anchor21)."
    },
    "exclusiveMinimum": {
      "$ref": "#/definitions/exclusiveMinimum",
      "description": "See [json-schema.org](http://json-schema.org/latest/json-schema-validation.html#anchor21)."
    },
    "maxLength": {
      "$ref": "#/definitions/maxLength",
      "description": "See [json-schema.org](http://json-schema.org/latest/json-schema-validation.html#anchor26)."
    },
    "minLength": {
      "$ref": "#/definitions/minLength",
      "description": "See [json-schema.org](http://json-schema.org/latest/json-schema-validation.html#anchor29)."
    },
    "pattern": {
      "$ref": "#/definitions/pattern",
      "description": "See [json-schema.org](http://json-schema.org/latest/json-schema-validation.html#anchor33)."
    },
    "maxItems": {
      "$ref": "#/definitions/maxItems",
      "description": "See [json-schema.org](http://json-schema.org/latest/json-schema-validation.html#anchor42)."
    },
    "minItems": {
      "$ref": "#/definitions/minItems",
      "description": "See [json-schema.org](http://json-schema.org/latest/json-schema-validation.html#anchor45)."
    },
    "uniqueItems": {
      "$ref": "#/definitions/uniqueItems",
      "description": "See [json-schema.org](http://json-schema.org/latest/json-schema-validation.html#anchor49)."
    },
    "enum": {
      "$ref": "#/definitions/enum",
      "description": "See [json-schema.org](http://json-schema.org/latest/json-schema-validation.html#anchor76)."
    },
    "multipleOf": {
      "$ref": "#/definitions/multipleOf",
      "description": "See [json-schema.org](http://json-schema.org/latest/json-schema-validation.html#anchor14)."
    }
  },
  "definitions": {
    "vendorExtension": {
      "description": "Any property starting with x- is valid.",
      "additionalProperties": true,
      "additionalItems": true
    },
    "primitivesItems": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": ["string", "number", "integer", "boolean", "array"]
        },
        "format": {
          "type": "string"
        },
        "items": {
          "$ref": "#/definitions/primitivesItems"
        },
        "collectionFormat": {
          "$ref": "#/definitions/collectionFormat"
        },
        "default": {
          "$ref": "#/definitions/default"
        },
        "maximum": {
          "$ref": "#/definitions/maximum"
        },
        "exclusiveMaximum": {
          "$ref": "#/definitions/exclusiveMaximum"
        },
        "minimum": {
          "$ref": "#/definitions/minimum"
        },
        "exclusiveMinimum": {
          "$ref": "#/definitions/exclusiveMinimum"
        },
        "maxLength": {
          "$ref": "#/definitions/maxLength"
        },
        "minLength": {
          "$ref": "#/definitions/minLength"
        },
        "pattern": {
          "$ref": "#/definitions/pattern"
        },
        "maxItems": {
          "$ref": "#/definitions/maxItems"
        },
        "minItems": {
          "$ref": "#/definitions/minItems"
        },
        "uniqueItems": {
          "$ref": "#/definitions/uniqueItems"
        },
        "enum": {
          "$ref": "#/definitions/enum"
        },
        "multipleOf": {
          "$ref": "#/definitions/multipleOf"
        }
      },
      "patternProperties": {
        "^x-": {
          "$ref": "#/definitions/vendorExtension"
        }
      }
    },
    "collectionFormat": {
      "type": "string",
      "enum": ["csv", "ssv", "tsv", "pipes"],
      "default": "csv"
    },
    "default": {},
    "maximum": {
      "type": "number"
    },
    "exclusiveMaximum": {
      "type": "boolean",
      "default": false
    },
    "minimum": {
      "type": "number"
    },
    "exclusiveMinimum": {
      "type": "boolean",
      "default": false
    },
    "maxLength": {
      "$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveInteger"
    },
    "minLength": {
      "$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveIntegerDefault0"
    },
    "pattern": {
      "type": "string",
      "format": "regex"
    },
    "maxItems": {
      "$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveInteger"
    },
    "minItems": {
      "$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveIntegerDefault0"
    },
    "uniqueItems": {
      "type": "boolean",
      "default": false
    },
    "enum": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true
    },
    "multipleOf": {
      "type": "number",
      "minimum": 0,
      "exclusiveMinimum": 0
    },
    "collectionFormatWithMulti": {
      "type": "string",
      "enum": ["csv", "ssv", "tsv", "pipes", "multi"],
      "default": "csv"
    }
  },
  "description": "Parameters that are appended to the URL. For example, in `/items?id=###`, the query parameter is id",
  "$id": "https://raw.githubusercontent.com/eXigentCoder/swagger-spec-express/master/lib/schemas/query-parameter-sub-schema.json"
}
